site_name: "Prompting with Purpose"
site_description: "Making Friends with AI — A Crash Course in Thinking Together"
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  icon:
    annotation: material/plus-circle-outline

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
nav:
  - "Home": "index.md"
  - "Introduction": "introduction.md"

  - "Foundations":
      - "Understanding AI Basics": "understanding_ai_basics.md"

  - "Core Techniques":
      - "First Principles Thinking": "first_principles_thinking.md"
      - "Chain of Thought Prompting": "chain_of_thought_prompting.md"
      - "Meta Prompting": "meta_prompting.md"

  - "Responsible AI Use":
      - "Verify Your Results": "results_verification.md"
      - "Ethical Use of AI": "ethical_use_of_ai.md"

  - "Practical Guidance":
      - "Practical Applications and Tool Tips": "practical_applications_and_tool_tips.md"
      - "Activities": "activities.md"

  - "Wrap-Up":
      - "Conclusion": "conclusion.md"
      - "References": "references.md"

  - "Appendix":
      - "Advanced Prompting Topics": "appendix.md"
      - "Prompt Library":
          - "Writing Prompts": "a_writing_prompts.md"
          - "Learning Prompts": "b_learning_prompts.md"
          - "Problem Solving": "c_problem_solving_prompts.md"
          - "Business Prompts": "d_business_prompts.md"
